<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3271bc43-ca89-4b9b-bbec-2f314aef847d</elementGuidId>
    <imagePath></imagePath>
    <name>span_diffLineContextPopup</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[5]/div[1]/main[1]/turbo-frame[1]/div[1]/react-app[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[1]/td[4]/code[1]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>body:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(5) &gt; div:nth-of-type(1) &gt; main:nth-of-type(1) &gt; turbo-frame:nth-of-type(1) &gt; div:nth-of-type(1) &gt; react-app:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(${span_diffLineContextPopup_divNthOfType}) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; table:nth-of-type(1) &gt; tbody:nth-of-type(1) &gt; tr:nth-of-type(${span_diffLineContextPopup_trNthOfType}) &gt; td:nth-of-type(4) &gt; code:nth-of-type(1) &gt; div:nth-of-type(1) &gt; span:nth-of-type(${span_diffLineContextPopup_spanNthOfType})</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>tr:nth-child(${span_diffLineContextPopup_trNthChild}) &gt; td:nth-child(4) &gt; .diff-text &gt; .diff-text-inner &gt; span:nth-child(${span_diffLineContextPopup_spanNthChild}) &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>