<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c4078267-32f9-469b-89be-819c82509d5e</elementGuidId>
    <imagePath></imagePath>
    <name>span_abcKatalonAitrueTest4</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/app-permissions[1]/app-work-item-details-page[1]/div[1]/div[1]/app-qc-work-item-forms[1]/div[1]/div[1]/div[1]/app-qc-work-item-queries[1]/div[2]/app-qc-work-item-query[75]/div[1]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>app-qc-work-item-query:nth-of-type(75) [class="query-card__title"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>app-qc-work-item-query:nth-child(75) &gt; .card &gt; .card__content &gt; .query-card__title</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_qc_worklist/appScopedStyles_object</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>