<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>133534bb-28e2-4121-bfb0-2becd15b45c4</elementGuidId>
    <imagePath></imagePath>
    <name>crShadowDom_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-micro-portal-layout[1]/div[1]/main[1]/app-micro-app[1]/app-scoped-styles[1]/cr-shadow-dom[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="app-scoped-styles"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#app-scoped-styles</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>