<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5616f0b1-3470-4e2c-aa79-cc0a90bdbd2c</elementGuidId>
    <imagePath></imagePath>
    <name>label_yes</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//cr-shadow-dom-portal/div[1]/div[1]/div[2]/app-questionnaire[1]/div[1]/div[1]/div[1]/cr-collapsible-panel[1]/details[1]/section[1]/div[1]/imgsh-form[1]/div[1]/div[1]/form[1]/imgsh-form-node-renderer[1]/imgsh-form-screen[1]/div[1]/imgsh-form-node-renderer[1]/imgsh-form-field[2]/imgsh-form-field-wrapper[1]/div[1]/div[1]/div[1]/imgsh-form-field-renderer[1]/div[1]/imgsh-form-list-field[1]/imgsh-radio-group[1]/div[1]/div[1]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.root &gt; [for="cr-radio-qlaul-34"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"group-question-2-edit-test\"] label &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_subjects_list_study_combined_view/crShadowDom_object6</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
</WebElementEntity>