<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>38c8a692-d822-4c13-b270-78c50680915b</elementGuidId>
    <imagePath></imagePath>
    <name>appScopedStyles_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-micro-portal-layout[1]/div[1]/main[1]/app-micro-app[1]/app-permitted[1]/app-scoped-styles[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>app-scoped-styles</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>app-scoped-styles</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>