<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9d4e0157-2310-4471-925c-c07599c0cfc1</elementGuidId>
    <imagePath></imagePath>
    <name>div_selectOption</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(4) &gt; .ant-select-dropdown &gt; div &gt; .rc-virtual-list &gt; .rc-virtual-list-holder &gt; div &gt; .rc-virtual-list-holder-inner &gt; div &gt; .ant-select-item-option-content &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>