<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b153f8e7-cc4d-4c36-adea-d7743d668d6c</elementGuidId>
    <imagePath></imagePath>
    <name>item_conversationTurns</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/main[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/article[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/ul[1]/li[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>ul:nth-child(${item_conversationTurns_ulNthChild}) &gt; li:nth-of-type(${item_conversationTurns_liNthOfType})</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"conversation-turn-4\"] li &gt;&gt; nth=${item_conversationTurns_nth}</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>