<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>085950a7-b0eb-4385-a40f-357217fa32a9</elementGuidId>
    <imagePath></imagePath>
    <name>span_summary</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[3]/div[1]/div[2]/div[1]/div[1]/section[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[4]/div[7]/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[3]/td[3]/div[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="_4t3i1ylp\ _kqswh2mm\ _bfhkfg4m\ _nt751r31\ _49pcglyw\ _1hvw1o36\ _7psyru3m\ _irr3i1yw\ _5sagru3m\ _80om1qgj\ _1qam5szm"] [class="css-yzhti3"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>tr:nth-child(3) &gt; td:nth-child(3) &gt; ._2rko1sit &gt; .css-yzhti3</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>