<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7504a10a-7b20-4f34-a2e6-a2befe440bf1</elementGuidId>
    <imagePath></imagePath>
    <name>button_namespace2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/main[1]/div[3]/div[1]/div[1]/div[1]/section[1]/div[1]/form[1]/div[2]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#var-namespace</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'data-testid Dashboard template variables Variable Value DropDown value link text &gt; ta-ka-7584-68-1745832603') and equals(@id,'var-namespace') and equals(@title,'&gt; ta-ka-7584-68-1745832603') and equals(@text,'&gt; ta-ka-7584-68-1745832603')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"data-testid Dashboard template variables Variable Value DropDown value link text \\&gt; ta-ka-7584-68-1745832603\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>data-testid Dashboard template variables Variable Value DropDown value link text &gt; ta-ka-7584-68-1745832603</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>var-namespace</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>&gt; ta-ka-7584-68-1745832603</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>&gt; ta-ka-7584-68-1745832603</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
</WebElementEntity>