<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>40329524-d4c1-4d23-a9cb-3a4e269f572e</elementGuidId>
    <imagePath></imagePath>
    <name>button_kipActions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[3]/div[2]/main[1]/span[1]/div[1]/div[1]/div[3]/div[2]/div[1]/div[1]/section[1]/div[1]/div[1]/div[2]/div[1]/div[3]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(${button_kipActions_divNthOfType}) &gt; [class="${button_kipActions_class}"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'platform-board-kit.ui.swimlane.link-button') and equals(@text,'KIP-5057
            [Phase 2] Separate data of AUT per environment using domain URL
            (no subtasks)
            status
            IN PROGRESS')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"platform-board-kit\\.ui\\.swimlane\\.link-button\"] &gt;&gt; nth=${button_kipActions_nth}</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>platform-board-kit.ui.swimlane.link-button</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>KIP-5057
        [Phase 2] Separate data of AUT per environment using domain URL
        (no subtasks)
        status
        IN PROGRESS</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>