<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f2fa86a4-1ace-454c-a46e-917ac9981477</elementGuidId>
    <imagePath></imagePath>
    <name>div_ctasConsiderations</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[1]/div[3]/main[1]/div[3]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="yfMjpkSCQBUG-SuvKWC1Mg\=\=\ pXSx0J9bHQFDahmE\+CryWA\=\=\ undefined\ SynT6ZmEr-pX\+3AI2kY68g\=\="]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.yfMjpkSCQBUG-SuvKWC1Mg\\=\\= &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>