<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a3f53c69-bea5-4c98-978a-ee347d2bd526</elementGuidId>
    <imagePath></imagePath>
    <name>button_save6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/app-study-configuration[1]/div[1]/div[1]/app-high-level-read-configure[1]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.header .button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Save')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Save\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Save</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_dashboard/appScopedStyles_object9</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>