<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8adf1245-2058-4193-b31f-0dfbf986437f</elementGuidId>
    <imagePath></imagePath>
    <name>button_trigger</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//cr-shadow-dom-portal/div[1]/div[1]/app-query-templates[1]/app-query-templates-table[1]/div[1]/cr-data-table[1]/div[1]/div[3]/cr-table[1]/table[1]/tbody[1]/tr[1]/td[1]/app-query-template-action[1]/cr-table-actions[1]/cr-dropdown-menu[1]/cr-popover-container[1]/trigger[1]/cr-button[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.inline-block .button</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>trigger button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_dashboard/crShadowDom_object</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>