<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7c86b89c-a43c-4d72-ac25-5ac1a3c6ad07</elementGuidId>
    <imagePath></imagePath>
    <name>button_noSkipVisit</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-dashboard-layout[1]/div[1]/app-header[1]/div[1]/header[1]/div[1]/div[1]/nav[1]/ul[1]/li[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li &gt; [type="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'SUS_NoSkipVisitAvailable-002')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test=\"nav\\.header\\.studies\"] button</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>SUS_NoSkipVisitAvailable-002</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>