<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7a82182a-507e-4fa3-a395-ea6e3d5e5470</elementGuidId>
    <imagePath></imagePath>
    <name>button_addForm6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/app-study-configuration[1]/div[1]/div[1]/div[2]/div[2]/app-data-collection[1]/app-warning-page[1]/div[1]/app-data-collection[1]/div[3]/app-collection[1]/table[1]/tbody[1]/tr[2]/td[2]/app-add-button-wrapper[1]/imgsh-add-form-button[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>imgsh-add-form-button &gt; .button</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"+ Add Form\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_dashboard/appScopedStyles_object9</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>