<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6c99bd09-64a6-421c-9356-706753d34ed3</elementGuidId>
    <imagePath></imagePath>
    <name>div_subjectNumberFormatInfo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/app-study-configuration[1]/div[1]/div[1]/div[2]/div[2]/app-subjects-config[1]/app-subject-form[1]/form[1]/div[1]/div[1]/app-form-config-section[1]/div[1]/div[2]/app-id-format[1]/form[1]/div[1]/app-form-field[3]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>app-form-field:nth-of-type(3) &gt; .full-width</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>app-form-field:nth-child(4) &gt; .full-width</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_dashboard/appScopedStyles_object9</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>