<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ee1c831d-bba6-4755-9cfe-29a7585811b4</elementGuidId>
    <imagePath></imagePath>
    <name>div_quicklinkList</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-dashboard-layout[1]/div[1]/app-header[1]/div[1]/app-quicklink-list[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="es-quicklinks\ --with-bg"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>app-quicklink-list div &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>