<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f40805aa-ca37-46f7-9ef0-fc46fb0967a6</elementGuidId>
    <imagePath></imagePath>
    <name>header_globalDashboard</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-dashboard-layout[1]/div[1]/app-header[1]/div[1]/header[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="es-fixed-global-header"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>app-header header</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>