<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>875e0020-952b-4395-8bea-2e68a87bdfc8</elementGuidId>
    <imagePath></imagePath>
    <name>link_registerSiteJoinStudy</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-dashboard-layout[1]/div[1]/main[1]/page-body[1]/div[1]/app-global-dashboard[1]/app-widget-list[1]/div[1]/temp-dynamic[1]/join-study-widget[1]/e-widget[1]/section[1]/e-widget-body[1]/div[1]/div[1]/div[1]/p[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>body:nth-of-type(1) &gt; app-root:nth-of-type(1) &gt; app-dashboard-layout:nth-of-type(1) &gt; div:nth-of-type(1) &gt; main:nth-of-type(1) &gt; page-body:nth-of-type(1) &gt; div:nth-of-type(1) &gt; app-global-dashboard:nth-of-type(1) &gt; app-widget-list:nth-of-type(1) &gt; div:nth-of-type(1) &gt; temp-dynamic:nth-of-type(1) &gt; join-study-widget:nth-of-type(1) &gt; e-widget:nth-of-type(1) &gt; section:nth-of-type(1) &gt; e-widget-body:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; p:nth-of-type(2) &gt; a:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'Register a Site / Join a Study')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Register a Site / Join a Study\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Register a Site / Join a Study</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
</WebElementEntity>