<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>418a3844-8bfb-4b0b-9c65-41cf36255ec2</elementGuidId>
    <imagePath></imagePath>
    <name>select_employeeDoor</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[10]/div[2]/div[3]/div[2]/span[1]/select[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="selDiv"] &gt; .inline-block-display</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'Employee_Door') and equals(@name,'Employee.Door')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#door-select #Employee_Door</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>Employee_Door</value>
        <webElementGuid>c234667e-46e0-49a7-9fd1-073bddb14cc8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>Employee.Door</value>
        <webElementGuid>c234667e-46e0-49a7-9fd1-073bddb14cc8</webElementGuid>
    </webElementProperties>
</WebElementEntity>