<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f5746b8f-7310-44df-a590-285e2cda5b73</elementGuidId>
    <imagePath></imagePath>
    <name>link_filesChanged3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[5]/div[1]/main[1]/run-summary[1]/turbo-frame[1]/div[1]/div[1]/div[2]/nav[1]/a[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.tabnav-tabs &gt; a:nth-of-type(4)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'{{url}}') and equals(@text,'Files changed 3')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"Files changed 3\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Files changed 3</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
</WebElementEntity>