<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f81e116f-dabe-4571-8f18-a090e6aba832</elementGuidId>
    <imagePath></imagePath>
    <name>button_trueTestKanbanBoard</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/div[2]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/nav[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="_1tnq1l7b\ _1wgmidpf\ _17bz1r31\ _e0gcglyw\ _15451o36\ _16hgr01l\ _1w901kw7\ _12r21wq8\ _1bk61b66\ _davf1jma\ _u1mb1j9a\ _1fh11kw7\ _ksby1kw7\ css-8ut1ye"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'navigation-apps.scope-switcher-trigger-button') and equals(@text,'TrueTest Kanban Board
            Board')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"navigation-apps\\.scope-switcher-trigger-button\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>navigation-apps.scope-switcher-trigger-button</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>TrueTest Kanban Board
        Board</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
</WebElementEntity>