<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>68224c9d-88d6-4539-a5b9-baeaf192d826</elementGuidId>
    <imagePath></imagePath>
    <name>button_admin</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\ MuiButton-root\ MuiButton-outlined\ MuiButton-outlinedBglight900\ MuiButton-sizeMedium\ MuiButton-outlinedSizeMedium\ MuiButton-colorBglight900\ MuiButton-disableElevation\ MuiButton-root\ MuiButton-outlined\ MuiButton-outlinedBglight900\ MuiButton-sizeMedium\ MuiButton-outlinedSizeMedium\ MuiButton-colorBglight900\ MuiButton-disableElevation\ KuiButton-neutral\ css-srp0js"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Admin')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:has-text=/^Admin$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Admin</value>
        <webElementGuid>ec91050f-a85c-41ca-87d7-c67063aea66c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>ec91050f-a85c-41ca-87d7-c67063aea66c</webElementGuid>
    </webElementProperties>
</WebElementEntity>