<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7c39ed98-a696-4e87-81be-58f5982212af</elementGuidId>
    <imagePath></imagePath>
    <name>link_proMovement</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/ul[1]/li[7]/div[1]/ul[1]/li[8]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#nav-col-container li:nth-of-type(8) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/dock-management/Reports/ProMovement') and equals(@text,'Pro Movement')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:text=\"Pro Movement\"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/dock-management/Reports/ProMovement</value>
        <webElementGuid>c234667e-46e0-49a7-9fd1-073bddb14cc8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Pro Movement</value>
        <webElementGuid>c234667e-46e0-49a7-9fd1-073bddb14cc8</webElementGuid>
    </webElementProperties>
</WebElementEntity>