<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>af452e3c-10ea-4fbc-bd9e-b1f66665fc82</elementGuidId>
    <imagePath></imagePath>
    <name>p_dateTime</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[6]/p[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="ant-table-cell\ ant-table-cell-row-hover"] &gt; p</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'{{date_time}} {{date_time}} UTC -- {{date_time}} {{date_time}} UTC')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>tr:nth-child(3) &gt; td:nth-child(6) &gt; p</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>{{date_time}} {{date_time}} UTC -- {{date_time}} {{date_time}} UTC</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
</WebElementEntity>