<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3793a2db-1f7d-4472-817e-121caaab1475</elementGuidId>
    <imagePath></imagePath>
    <name>div_procurementSection</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/form[1]/div[2]/div[2]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/table[1]/tbody[1]/tr[1]/td[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[11]/div[1]/div[1]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="pt1\:_UISnvr\:0\:nvgpgl2_groupNode_procurement"] &gt; div:nth-of-type(2)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div[title=\"Procurement\"] div &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>