<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b071da49-12d4-4316-a8c5-4b8c25768313</elementGuidId>
    <imagePath></imagePath>
    <name>link_blkDailyRatesReport</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/form[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[2]/td[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'pt1:comp_dtrt8272075510') and equals(@href,'{{url}}?bipublisherEntry&amp;{{url}}open&amp;{{url}}&amp;bipPath=%2FCustom%2FVS_APR22%2FBLK_DAILY_RATES_REPORT.xdo&amp;bipParams=%7B%22_xmode%22%3A%222%22%2C%22_sTkn%22%3A%2290cefb8b1824a6f668b%22%2C%22_xiasynch%22%3A%22%22%2C%22_xpf%22%3A%22%22%2C%22_xpt%22%3A%220%22%2C%22_dFlag%22%3A%22false%22%2C%22_edIndex%22%3A%220%22%2C%22_dIndex%22%3A%220%22%2C%22_rToken%22%3A%22%22%2C%22_ranDiag%22%3A%22false%22%2C%22_xdo%22%3A%22%2FCustom%2FVS_APR22%2FBLK_DAILY_RATES_REPORT.xdo%22%2C%22_xt%22%3A%22BLK_DAILY_RATES_REPORT%22%2C%22_xf%22%3A%22pdf%22%2C%22_xautorun%22%3A%22true%22%7D&amp;_linkToReport=true')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}?bipublisherEntry&amp;{{url}}open&amp;{{url}}&amp;bipPath=%2FCustom%2FVS_APR22%2FBLK_DAILY_RATES_REPORT.xdo&amp;bipParams=%7B%22_xmode%22%3A%222%22%2C%22_sTkn%22%3A%2290cefb8b1824a6f668b%22%2C%22_xiasynch%22%3A%22%22%2C%22_xpf%22%3A%22%22%2C%22_xpt%22%3A%220%22%2C%22_dFlag%22%3A%22false%22%2C%22_edIndex%22%3A%220%22%2C%22_dIndex%22%3A%220%22%2C%22_rToken%22%3A%22%22%2C%22_ranDiag%22%3A%22false%22%2C%22_xdo%22%3A%22%2FCustom%2FVS_APR22%2FBLK_DAILY_RATES_REPORT.xdo%22%2C%22_xt%22%3A%22BLK_DAILY_RATES_REPORT%22%2C%22_xf%22%3A%22pdf%22%2C%22_xautorun%22%3A%22true%22%7D&amp;_linkToReport=true</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>pt1:comp_dtrt8272075510</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
</WebElementEntity>