<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d0a2898e-3348-4208-9841-e6745caa80ef</elementGuidId>
    <imagePath></imagePath>
    <name>p_developer</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/div[3]/ul[1]/li[2]/p[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>