<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>be741e2c-a2e7-4bfd-97a7-70d1a72ceb03</elementGuidId>
    <imagePath></imagePath>
    <name>span_back</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/button[1]/span[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="svg-inline--fa\ fa-angle-left\ MuiIcon-root\ css-1s7lwsc"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"userProfile\\.button\\.back\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>