<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>09f8d5e5-407f-4349-ac40-4472697b7fdc</elementGuidId>
    <imagePath></imagePath>
    <name>div_uploadSections_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//cr-shadow-dom-portal/div[1]/div[1]/app-site-assessment-overview[1]/site-details[1]/div[1]/div[2]/div[2]/div[1]/site-details-tab[2]/site-modalities[1]/div[1]/div[1]/tab-menu[1]/div[1]/div[2]/tab-menu-item[2]/div[1]/div[2]/div[4]/div[2]/modality-device-list[1]/cr-cdk-simple-table[1]/div[1]/table[1]/tbody[1]/tr[1]/td[6]/app-device-activity-cell[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>cr-shadow-dom-portal:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; app-site-assessment-overview:nth-of-type(1) &gt; site-details:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; site-details-tab:nth-of-type(2) &gt; site-modalities:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; tab-menu:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; tab-menu-item:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(4) &gt; div:nth-of-type(2) &gt; modality-device-list:nth-of-type(1) &gt; cr-cdk-simple-table:nth-of-type(1) &gt; div:nth-of-type(1) &gt; table:nth-of-type(1) &gt; tbody:nth-of-type(1) &gt; tr:nth-of-type(${div_uploadSections_trNthOfType}) &gt; td:nth-of-type(6) &gt; app-device-activity-cell:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'open-uploader-queries')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>tab-menu-item:nth-child(2) &gt; div &gt; .card &gt; div:nth-child(4) &gt; div:nth-child(2) &gt; modality-device-list &gt; cr-cdk-simple-table &gt; div &gt; .cdk-table &gt; tbody &gt; tr:nth-child(${div_uploadSections_trNthChild}) &gt; td:nth-child(6) &gt; .inline-block &gt; div &gt; .link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>open-uploader-queries</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_siteservice_service_site_assessments/crShadowDom_object2</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
</WebElementEntity>