<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cbcfaf68-7695-4647-be0e-b21c52f5f812</elementGuidId>
    <imagePath></imagePath>
    <name>link_dockedBay</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[10]/div[2]/div[9]/table[1]/tbody[1]/tr[2]/td[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.pro-docked [class="Pro"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test=\"DCK\\|Docked Bay 41\\, STAGE-IT\"] &gt;&gt; internal:text=\"I980000289\"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>c234667e-46e0-49a7-9fd1-073bddb14cc8</webElementGuid>
    </webElementProperties>
</WebElementEntity>