<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cf2ff43a-11a4-4a68-b8a2-f67aa9b65062</elementGuidId>
    <imagePath></imagePath>
    <name>button_quality</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\ MuiButton-root\ MuiButton-outlined\ MuiButton-outlinedBglight900\ MuiButton-sizeMedium\ MuiButton-outlinedSizeMedium\ MuiButton-colorBglight900\ MuiButton-disableElevation\ MuiButton-root\ MuiButton-outlined\ MuiButton-outlinedBglight900\ MuiButton-sizeMedium\ MuiButton-outlinedSizeMedium\ MuiButton-colorBglight900\ MuiButton-disableElevation\ KuiButton-neutral\ css-srp0js"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Quality')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:has-text=/^Quality$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Quality</value>
        <webElementGuid>33f9be2d-29a8-43d5-a9f4-1354b50a16cf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>33f9be2d-29a8-43d5-a9f4-1354b50a16cf</webElementGuid>
    </webElementProperties>
</WebElementEntity>