<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c89a697e-9bf0-4288-82bf-bc66b808d8a6</elementGuidId>
    <imagePath></imagePath>
    <name>button_cancel</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[3]/div[1]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiButtonBase-root\ MuiButton-root\ MuiButton-outlined\ MuiButton-outlinedBglight900\ MuiButton-sizeMedium\ MuiButton-outlinedSizeMedium\ MuiButton-colorBglight900\ MuiButton-disableElevation\ MuiButton-root\ MuiButton-outlined\ MuiButton-outlinedBglight900\ MuiButton-sizeMedium\ MuiButton-outlinedSizeMedium\ MuiButton-colorBglight900\ MuiButton-disableElevation\ KuiButton-neutral\ css-1mzvo3n"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Cancel')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Cancel\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Cancel</value>
        <webElementGuid>ec91050f-a85c-41ca-87d7-c67063aea66c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>ec91050f-a85c-41ca-87d7-c67063aea66c</webElementGuid>
    </webElementProperties>
</WebElementEntity>