<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5c70d955-bfdd-4fc0-b189-544bff53ea6b</elementGuidId>
    <imagePath></imagePath>
    <name>div_loadingIndicator</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/loading-indicator[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="es-loading-indicator\ -es-visible\ -es-fullscreen"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>loading-indicator div</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>