<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ca6ae886-941e-4288-b9e6-c7fbf0d5907b</elementGuidId>
    <imagePath></imagePath>
    <name>faIcon_object3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//cr-shadow-dom-portal/div[1]/cr-toast-group[1]/div[1]/cr-toast[2]/div[1]/button[1]/cr-icon[1]/fa-icon[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>cr-shadow-dom-portal:nth-of-type(1) &gt; div:nth-of-type(1) &gt; cr-toast-group:nth-of-type(1) &gt; div:nth-of-type(1) &gt; cr-toast:nth-of-type(2) &gt; div:nth-of-type(1) &gt; button:nth-of-type(1) &gt; cr-icon:nth-of-type(1) &gt; fa-icon:nth-of-type(1) &gt; svg:nth-of-type(1)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>cr-toast-group button &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_subjects_list_study/crShadowDom_object5</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>