<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e4306488-bdf0-464c-ad0f-4e9b43972232</elementGuidId>
    <imagePath></imagePath>
    <name>input_signOut2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[4]/main[1]/div[1]/div[3]/div[1]/div[2]/form[1]/input[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="btn\ btn-sm\ m-0"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'commit') and equals(@type,'submit')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>input[value=\"Sign out\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>commit</value>
        <webElementGuid>8305829a-2b2f-4c8e-bf8f-a92b1c012308</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>submit</value>
        <webElementGuid>8305829a-2b2f-4c8e-bf8f-a92b1c012308</webElementGuid>
    </webElementProperties>
</WebElementEntity>