<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b504e352-0c3a-4495-b534-ea75b45f21ff</elementGuidId>
    <imagePath></imagePath>
    <name>link_clientCode</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/main[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[3]/td[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>tr:nth-of-type(3) &gt; td:nth-of-type(3) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/env/qa/aut/KA-7584-68')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"KA-7584-68\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/env/qa/aut/KA-7584-68</value>
        <webElementGuid>8305829a-2b2f-4c8e-bf8f-a92b1c012308</webElementGuid>
    </webElementProperties>
</WebElementEntity>