<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8f4a5e4a-630f-4141-bf6c-244b5180b1fc</elementGuidId>
    <imagePath></imagePath>
    <name>link_staging</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/main[1]/nav[1]/ol[1]/li[1]/a[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.ant-breadcrumb-link &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'staging')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text=/^staging$/ &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>staging</value>
        <webElementGuid>ba3fe8a3-b36b-4743-9621-89a47fdaa517</webElementGuid>
    </webElementProperties>
</WebElementEntity>