<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1ad4e949-c6ad-4894-8cf5-63ffa5191d34</elementGuidId>
    <imagePath></imagePath>
    <name>link_orderPurchased</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[2]/div[1]/div[2]/div[1]/div[1]/div[1]/div[3]/div[3]/div[1]/div[1]/ul[1]/li[2]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="account-menu__links"] &gt; li:nth-of-type(2) &gt; a</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/orders-buy.html') and equals(@text,'Đơn hàng đã mua')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"\u0110\u01a1n h\u00e0ng \u0111\u00e3 mua\"s &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/orders-buy.html</value>
        <webElementGuid>2acf07fb-47af-4ffd-8e74-1d49995c2e55</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Đơn hàng đã mua</value>
        <webElementGuid>2acf07fb-47af-4ffd-8e74-1d49995c2e55</webElementGuid>
    </webElementProperties>
</WebElementEntity>