<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8e4fac7a-c2b6-4ef2-b8d5-745de349a1f9</elementGuidId>
    <imagePath></imagePath>
    <name>div_dashboardWidgets</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[10]/div[1]/div[3]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(3) &gt; div:nth-of-type(${div_dashboardWidgets_divNthOfType})</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Flowcharts (9)')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div[title=\"${div_dashboardWidgets_divTitle}\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Flowcharts (9)</value>
        <webElementGuid>ba3fe8a3-b36b-4743-9621-89a47fdaa517</webElementGuid>
    </webElementProperties>
</WebElementEntity>