<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>05e893a7-c06e-4ea3-a8fc-9af3f287c4f1</elementGuidId>
    <imagePath></imagePath>
    <name>span_diffLineChange_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[5]/div[1]/main[1]/turbo-frame[1]/div[1]/div[1]/div[1]/diff-file-filter[1]/diff-layout[1]/div[3]/div[2]/copilot-diff-entry[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[1]/td[4]/span[1]/span[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="code-review\ blob-code\ blob-code-addition\ js-file-line\ is-hovered"] &gt; .blob-code-inner &gt; span:nth-of-type(1)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>tr:nth-child(${span_diffLineChange_trNthChild}) &gt; .code-review &gt; .blob-code-inner &gt; span &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>