<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6e67a0c7-092d-4fee-a65d-f0857f24ff21</elementGuidId>
    <imagePath></imagePath>
    <name>button_videoPlayer</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/div[1]/div[3]/div[4]/div[3]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[6]/section[1]/div[3]/div[2]/div[1]/div[1]/span[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="VYBDae-Bz112c-LgbsSe\ VYBDae-Bz112c-LgbsSe-OWXEXe-ornU0b\ VYBDae-Bz112c-LgbsSe-OWXEXe-SfQLQb-suEOdc\ QZj8kf\ FER5Nb"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Video Player\"s &gt;&gt; internal:label=\"Play keyboard shortcut k\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>