<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>4740b79b-438a-4502-a278-e00c77758e4b</elementGuidId>
    <imagePath></imagePath>
    <name>button_unmute</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]/div[1]/div[3]/div[4]/div[3]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[6]/section[1]/div[3]/div[2]/div[2]/div[2]/div[1]/span[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="yvd7zb"] [class="pYTkkf-Bz112c-LgbsSe\ pYTkkf-Bz112c-LgbsSe-OWXEXe-SfQLQb-suEOdc\ razjvf"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Unmute (m)\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>