<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c0cc5a18-fefa-4dec-943e-7be6567c20a8</elementGuidId>
    <imagePath></imagePath>
    <name>faIcon_query</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//cr-shadow-dom-portal/div[1]/div[1]/div[2]/div[1]/app-sidebar[1]/div[1]/app-query-list[1]/section[1]/div[2]/div[1]/div[1]/div[2]/cr-icon[1]/fa-icon[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="svg-inline--fa\ fa-hexagon-exclamation"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test=\"query-icon\"] svg</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_data_uploader/crShadowDom_object10</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
</WebElementEntity>