<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>ec654364-715f-4cc6-b21a-dd268eb75915</elementGuidId>
    <imagePath></imagePath>
    <name>td_dnsTypes</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/strong[1]/div[3]/table[1]/tbody[1]/tr[1]/td[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${td_dnsTypes_class}"] &gt; [class="index_type"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>tr:nth-child(${td_dnsTypes_trNthChild}) &gt; .index_type</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>