<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f6f47428-ea3f-4152-8048-f07fe3316145</elementGuidId>
    <imagePath></imagePath>
    <name>div_watch5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ytd-app[1]/div[1]/ytd-page-manager[1]/ytd-watch-flexy[1]/div[3]/div[1]/div[3]/ytd-player[1]/div[1]/div[1]/div[29]/div[1]/div[2]/div[1]/div[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>