<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>57389c25-a0e2-4e72-b887-f3c1caaebfbf</elementGuidId>
    <imagePath></imagePath>
    <name>div_accessTokenErrors</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[3]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[8]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${div_accessTokenErrors_class}"] &gt; [class="MuiDataGrid-cell\ MuiDataGrid-cell--textLeft"] &gt; [class=""]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"There seems to be a problem with your Personal Access Token. Please check its validity and permissions before proceeding.\"s &gt;&gt; nth=${div_accessTokenErrors_nth}</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>