<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>87f223b3-d713-41d8-869c-61843297309c</elementGuidId>
    <imagePath></imagePath>
    <name>item_testCaseManagement</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[3]/ul[1]/span[1]/li[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>span:nth-of-type(${item_testCaseManagement_spanNthOfType}) &gt; [class="MuiButtonBase-root\ MuiMenuItem-root\ MuiMenuItem-gutters\ MuiMenuItem-root\ MuiMenuItem-gutters\ css-1s2tu2m"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"${item_testCaseManagement_internalLabel}\"s &gt;&gt; li</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>