<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fa177e1b-1cba-4693-bee1-06c7da67432b</elementGuidId>
    <imagePath></imagePath>
    <name>button_actions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/aside[1]/nav[1]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.hidden-print &gt; button:nth-of-type(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'ACTIONS
            1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Actions1\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>ACTIONS
        1</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
</WebElementEntity>