<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>cbccc72a-736d-478f-8702-25a09e9c0242</elementGuidId>
    <imagePath></imagePath>
    <name>div_imFinished</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/main[1]/main[1]/gm-meeting-step--canvas[1]/section[1]/header[1]/section[1]/gm-finished-button[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="finished-button__shaker"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>gm-finished-button div &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>