<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>73f5be54-73bb-4139-b214-5cf7c27538e5</elementGuidId>
    <imagePath></imagePath>
    <name>div_tokenError</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[3]/div[1]/div[2]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiPaper-root\ MuiPaper-elevation\ MuiPaper-rounded\ MuiPaper-elevation0\ MuiAlert-root\ MuiAlert-colorError\ MuiAlert-standardError\ MuiAlert-standard\ css-f8290l"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.MuiStack-root &gt; .MuiPaper-root</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>