<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0b4cfe4a-474d-4080-970d-dfb0793458aa</elementGuidId>
    <imagePath></imagePath>
    <name>div_infoError2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/cr-modals-container[1]/cr-modal-opener[1]/cr-modal[1]/dialog[1]/div[1]/app-visit-modal[1]/form[1]/cr-modal-body[1]/div[5]/app-form-field[2]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(5) &gt; app-form-field:nth-of-type(2) .info-error</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div:nth-child(9) &gt; app-form-field:nth-child(2) &gt; .full-width &gt; .info-error</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_imaging_study_config/appScopedStyles_object</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>