<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fe402962-81a9-4c26-88c0-d617e1a8828e</elementGuidId>
    <imagePath></imagePath>
    <name>link_addCustomState</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/app-study-configuration[1]/div[1]/div[1]/div[2]/div[2]/app-subjects-config[1]/app-subject-form[1]/form[1]/div[1]/div[1]/app-form-config-section[1]/div[1]/div[2]/div[3]/app-states-form-part[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.flex &gt; .link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'add_custom_state') and equals(@text,'Add custom state')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"add_custom_state\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>add_custom_state</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Add custom state</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_imaging_study_config/appScopedStyles_object</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>