<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>187b9af4-4e63-4d26-b07d-ecb75d857ce0</elementGuidId>
    <imagePath></imagePath>
    <name>label_viewed3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[5]/div[1]/main[1]/turbo-frame[1]/div[1]/div[1]/div[1]/diff-file-filter[1]/diff-layout[1]/div[3]/div[2]/div[1]/div[2]/copilot-diff-entry[6]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>body:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(5) &gt; div:nth-of-type(1) &gt; main:nth-of-type(1) &gt; turbo-frame:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; diff-file-filter:nth-of-type(1) &gt; diff-layout:nth-of-type(1) &gt; div:nth-of-type(3) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; copilot-diff-entry:nth-of-type(6) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; form:nth-of-type(1) &gt; label:nth-of-type(1)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#diff-36ed64980c766189dbb935663407588d382b539a874eb71c99fef2172ea5924c &gt; .file-header &gt; .file-actions &gt; div &gt; .js-replace-file-header-review &gt; .js-toggle-user-reviewed-file-form &gt; .js-reviewed-toggle</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>