<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>19339ee0-dd77-448e-b031-160a0d304e81</elementGuidId>
    <imagePath></imagePath>
    <name>label_viewed2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[5]/div[1]/main[1]/turbo-frame[1]/div[1]/div[1]/div[1]/diff-file-filter[1]/diff-layout[1]/div[3]/div[2]/div[1]/div[2]/copilot-diff-entry[4]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/label[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="js-reviewed-toggle\ ml-2\ mr-1\ px-2\ py-1\ rounded-2\ f6\ text-normal\ d-flex\ flex-items-center\ border\ color-border-muted\ color-bg-accent\ color-border-accent"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#diff-8121b98464d0be3fefeb393d1a63f21348ca1f39d4af29dc8bf1f916be2cb331 &gt; .file-header &gt; .file-actions &gt; div &gt; .js-replace-file-header-review &gt; .js-toggle-user-reviewed-file-form &gt; .js-reviewed-toggle</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>