<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>965e865f-e66d-45de-a8a6-b3acd1cce26b</elementGuidId>
    <imagePath></imagePath>
    <name>label_viewed6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[5]/div[1]/main[1]/turbo-frame[1]/div[1]/div[1]/div[1]/div[1]/diff-file-filter[1]/diff-layout[1]/div[3]/div[2]/div[1]/div[2]/copilot-diff-entry[3]/div[1]/div[1]/div[2]/div[1]/div[1]/form[1]/label[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>