<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>2083b6c2-e7fc-4d42-9b25-a7b9e778d593</elementGuidId>
    <imagePath></imagePath>
    <name>span_diffLineChange25</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[5]/div[1]/main[1]/turbo-frame[1]/div[1]/div[1]/div[1]/div[1]/diff-file-filter[1]/diff-layout[1]/div[3]/div[2]/div[1]/div[2]/copilot-diff-entry[7]/div[1]/div[2]/div[1]/deferred-diff-lines[1]/table[1]/tbody[1]/tr[26]/td[4]/span[1]/span[8]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="code-review\ blob-code\ blob-code-addition\ js-file-line\ is-hovered"] span:nth-of-type(8)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>tr:nth-child(26) &gt; .code-review &gt; .blob-code-inner &gt; span:nth-child(8)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>