<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a6ca1aa1-5789-447e-b38a-234a6cde7289</elementGuidId>
    <imagePath></imagePath>
    <name>span_diffLineChange21</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[5]/div[1]/main[1]/turbo-frame[1]/div[1]/div[1]/div[1]/diff-file-filter[1]/diff-layout[1]/div[3]/div[2]/copilot-diff-entry[1]/div[1]/div[2]/div[1]/table[1]/tbody[1]/tr[27]/td[4]/span[1]/span[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="code-review\ blob-code\ blob-code-context\ js-file-line\ is-hovered"] [class="pl-en"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>tr:nth-child(27) &gt; td:nth-child(4) &gt; .blob-code-inner &gt; .pl-en</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>