<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>737ea5fa-2f6c-44d5-a471-879eb7657b5a</elementGuidId>
    <imagePath></imagePath>
    <name>span_diffLineChange6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[5]/div[1]/main[1]/turbo-frame[1]/div[1]/div[1]/div[1]/diff-file-filter[1]/diff-layout[1]/div[3]/div[2]/div[1]/div[2]/copilot-diff-entry[3]/div[1]/div[2]/div[1]/deferred-diff-lines[1]/table[1]/tbody[1]/tr[50]/td[4]/span[1]/span[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="code-review\ blob-code\ blob-code-addition\ js-file-line\ is-hovered"] [class="pl-s"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>tr:nth-child(50) &gt; .code-review &gt; .blob-code-inner &gt; .pl-s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>