<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>47636ede-49dd-43d3-aaf3-062cecd13dbc</elementGuidId>
    <imagePath></imagePath>
    <name>td_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[5]/div[1]/main[1]/turbo-frame[1]/div[1]/div[1]/div[1]/div[1]/diff-file-filter[1]/diff-layout[1]/div[3]/div[2]/div[1]/div[2]/copilot-diff-entry[7]/div[1]/div[2]/div[1]/deferred-diff-lines[1]/table[1]/tbody[1]/tr[28]/td[4]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="code-review\ blob-code\ blob-code-addition\ js-file-line\ is-hovered"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>deferred-diff-lines &gt; .diff-table &gt; tbody &gt; tr:nth-child(28) &gt; .code-review</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>