<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>17a71157-e32c-4113-8e1c-f123ce78bd5f</elementGuidId>
    <imagePath></imagePath>
    <name>button_automationStudy</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-micro-portal-layout[1]/div[1]/app-header[1]/div[1]/header[1]/div[1]/div[1]/nav[1]/ul[1]/li[4]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(4) &gt; [type="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'AUTOMATIONSTUDY01')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"AUTOMATIONSTUDY01\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>AUTOMATIONSTUDY01</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
</WebElementEntity>