<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1aee5a70-b738-443b-aa6b-ab463c58c4ac</elementGuidId>
    <imagePath></imagePath>
    <name>div_goalDetails</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/article[1]/main[1]/div[1]/div[1]/div[3]/div[1]/div[3]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.card-block</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test-id=\"card-content\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>