<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>32fcf61c-fb88-4bc5-afd5-edb0280f635b</elementGuidId>
    <imagePath></imagePath>
    <name>div_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/article[1]/main[1]/div[1]/div[1]/div[3]/section[1]/div[1]/div[1]/section[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="\36 78df5db6ff7de35a03be144"] [class="tw-flex\ tw-max-w-full\ tw-gap-4\ tw-items-center\ tw-mb-1\ tw-p-4\ \ tw-min-h-\[40px\]"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.card-with-hover-effect &gt; div &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>