<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>961926a2-ac0b-4732-84c5-66bd60ca9a3a</elementGuidId>
    <imagePath></imagePath>
    <name>div_object2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ytd-app[1]/ytd-miniplayer[1]/div[2]/div[1]/div[1]/div[1]/div[1]/ytd-player[1]/div[1]/div[1]/div[26]/div[2]/div[1]/div[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>