<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f9f04086-1ff9-42d0-a1bf-22c4801b0370</elementGuidId>
    <imagePath></imagePath>
    <name>link_home</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/ytd-app[1]/div[1]/div[2]/ytd-masthead[1]/div[4]/div[1]/ytd-topbar-logo-renderer[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#logo &gt; #logo</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'logo') and equals(@title,'Trang chủ YouTube') and equals(@href,'/')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#masthead a[title=\"Trang ch\u1ee7 YouTube\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>logo</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Trang chủ YouTube</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
</WebElementEntity>