<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0fcdbf9a-54d9-4341-a153-f3d559f96bb8</elementGuidId>
    <imagePath></imagePath>
    <name>link_qa2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/main[1]/header[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>a:nth-of-type(2)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/env/qa') and equals(@text,'QA')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text=/^QA$/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/env/qa</value>
        <webElementGuid>8305829a-2b2f-4c8e-bf8f-a92b1c012308</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>QA</value>
        <webElementGuid>8305829a-2b2f-4c8e-bf8f-a92b1c012308</webElementGuid>
    </webElementProperties>
</WebElementEntity>