<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5fd96aeb-8091-475b-b26d-ad55b093a3a2</elementGuidId>
    <imagePath></imagePath>
    <name>textarea_pasteVersionText</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/form[1]/div[1]/textarea[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[name="text1"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'inputText1') and equals(@name,'text1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>textarea[placeholder=\"Paste one version of a text here\\.\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>inputText1</value>
        <webElementGuid>8305829a-2b2f-4c8e-bf8f-a92b1c012308</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>text1</value>
        <webElementGuid>8305829a-2b2f-4c8e-bf8f-a92b1c012308</webElementGuid>
    </webElementProperties>
</WebElementEntity>