<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5e3e9ff2-f2ca-4546-bb8b-d82254110eb4</elementGuidId>
    <imagePath></imagePath>
    <name>link_dynamicObject</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/nav[1]/ol[1]/li[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(${link_dynamicObject_liNthOfType}) &gt; [class="MuiTypography-root\ MuiTypography-inherit\ MuiLink-root\ MuiLink-underlineAlways\ css-j5mzwn"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@text,'Katalon Cloud')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:text=\"${link_dynamicObject_internalText}\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Katalon Cloud</value>
        <webElementGuid>b6e89a31-3aa9-45a9-9425-519a7550ac18</webElementGuid>
    </webElementProperties>
</WebElementEntity>