<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a0ff4747-f2fd-4f21-9a2d-1ee9a488c30e</elementGuidId>
    <imagePath></imagePath>
    <name>link_navigateToTest</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[3]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[3]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="${link_navigateToTest_class}"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'${link_navigateToTest_href_variable}') and equals(@text,'TC-2853007 tesst 1')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"${link_navigateToTest_internalLabel}\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>TC-2853007 tesst 1</value>
        <webElementGuid>ec91050f-a85c-41ca-87d7-c67063aea66c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>${{link_navigateToTest_href_variable}}</value>
        <webElementGuid>ec91050f-a85c-41ca-87d7-c67063aea66c</webElementGuid>
    </webElementProperties>
</WebElementEntity>