<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d984fbdb-1a76-4029-bad7-46720764bd16</elementGuidId>
    <imagePath></imagePath>
    <name>button_submit5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//cr-shadow-dom-portal/div[1]/cr-modals-container[1]/cr-modal-opener[1]/cr-modal[1]/dialog[1]/div[1]/add-device-modal[1]/form[1]/cr-modal-body[1]/new-device-wizard[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(2) &gt; [type="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button') and equals(@text,'Submit')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>button &gt;&gt; internal:text=\"Submit\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Submit</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_dashboard/crShadowDom_object12</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>