<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8bfa445a-663e-4b61-a972-3ee349c39b89</elementGuidId>
    <imagePath></imagePath>
    <name>button_object3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//cr-shadow-dom-portal/div[1]/cr-modals-container[1]/cr-modal-opener[1]/cr-modal[1]/dialog[1]/div[1]/add-questionnaire-modal[1]/form[1]/cr-modal-body[1]/div[1]/imgsh-form[1]/div[1]/div[1]/form[1]/imgsh-form-node-renderer[1]/imgsh-form-screen[1]/div[1]/imgsh-form-node-renderer[1]/imgsh-form-field[6]/imgsh-form-field-wrapper[1]/div[1]/div[1]/div[1]/imgsh-form-field-renderer[1]/div[1]/imgsh-form-number-field[1]/imgsh-form-expandable-input-wrapper[1]/div[1]/div[1]/cr-input[1]/div[1]/div[2]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>cr-shadow-dom-portal:nth-of-type(1) &gt; div:nth-of-type(1) &gt; cr-modals-container:nth-of-type(1) &gt; cr-modal-opener:nth-of-type(1) &gt; cr-modal:nth-of-type(1) &gt; dialog:nth-of-type(1) &gt; div:nth-of-type(1) &gt; add-questionnaire-modal:nth-of-type(1) &gt; form:nth-of-type(1) &gt; cr-modal-body:nth-of-type(1) &gt; div:nth-of-type(1) &gt; imgsh-form:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; form:nth-of-type(1) &gt; imgsh-form-node-renderer:nth-of-type(1) &gt; imgsh-form-screen:nth-of-type(1) &gt; div:nth-of-type(1) &gt; imgsh-form-node-renderer:nth-of-type(1) &gt; imgsh-form-field:nth-of-type(6) &gt; imgsh-form-field-wrapper:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; imgsh-form-field-renderer:nth-of-type(1) &gt; div:nth-of-type(1) &gt; imgsh-form-number-field:nth-of-type(1) &gt; imgsh-form-expandable-input-wrapper:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; cr-input:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; button:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>imgsh-form-field:nth-child(7) &gt; imgsh-form-field-wrapper &gt; .card &gt; .card__content &gt; div &gt; imgsh-form-field-renderer &gt; div &gt; imgsh-form-number-field &gt; imgsh-form-expandable-input-wrapper &gt; .expandable-container &gt; div &gt; cr-input &gt; .fieldset-item &gt; .input-wrapper &gt; .buttons-wrapper &gt; button &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_dashboard/crShadowDom_object12</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>