<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d0299f54-4c9c-427f-bafa-f0b74cd1be26</elementGuidId>
    <imagePath></imagePath>
    <name>div_qualityNotification</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/cr-modals-container[1]/cr-modal-opener[1]/cr-modal[1]/dialog[1]/div[1]/app-query-create-modal[1]/form[1]/cr-modal-body[1]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="flex\ flex-grow\ items-center\ justify-end"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.recipient &gt; div:nth-child(2)</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_dashboard/appScopedStyles_object32</value>
        <webElementGuid>2acf07fb-47af-4ffd-8e74-1d49995c2e55</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>2acf07fb-47af-4ffd-8e74-1d49995c2e55</webElementGuid>
    </webElementProperties>
</WebElementEntity>