<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6dffbcef-364c-4f81-a504-f158a9e3fab6</elementGuidId>
    <imagePath></imagePath>
    <name>div_studyCode</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/app-permissions[1]/app-worklist[1]/div[1]/div[1]/app-table[1]/cr-data-table[1]/div[1]/div[3]/cr-table[1]/table[1]/tbody[1]/tr[1]/td[4]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>td:nth-of-type(4) &gt; .truncate-cell</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.truncate-cell &gt; .truncate-cell &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_dashboard/appScopedStyles_object32</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>