<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f2443b0b-bd80-4fb8-ac91-e6403f41b8a8</elementGuidId>
    <imagePath></imagePath>
    <name>faIcon_object2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/app-permissions[1]/app-worklist[1]/div[1]/div[1]/app-table[1]/cr-data-table[1]/div[1]/div[3]/cr-table[1]/table[1]/tbody[1]/tr[2]/td[1]/app-actions[1]/cr-dropdown-menu[1]/cr-popover-container[1]/trigger[1]/cr-icon[1]/fa-icon[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>div:nth-of-type(1) &gt; app-permissions:nth-of-type(1) &gt; app-worklist:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; app-table:nth-of-type(1) &gt; cr-data-table:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(3) &gt; cr-table:nth-of-type(1) &gt; table:nth-of-type(1) &gt; tbody:nth-of-type(1) &gt; tr:nth-of-type(2) &gt; td:nth-of-type(1) &gt; app-actions:nth-of-type(1) &gt; cr-dropdown-menu:nth-of-type(1) &gt; cr-popover-container:nth-of-type(1) &gt; trigger:nth-of-type(1) &gt; cr-icon:nth-of-type(1) &gt; fa-icon:nth-of-type(1) &gt; svg:nth-of-type(1)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>tr:nth-child(2) &gt; td &gt; app-actions &gt; cr-dropdown-menu &gt; .dropdown &gt; .inline-block &gt; .ml-2 &gt; .ng-fa-icon &gt; .svg-inline--fa</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_dashboard/appScopedStyles_object32</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
</WebElementEntity>