<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d9935aa0-3b13-4445-bf07-8a0b8bbda1a2</elementGuidId>
    <imagePath></imagePath>
    <name>faIcon_object15</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//cr-shadow-dom-portal/div[1]/div[2]/app-subject-table[1]/cr-data-table[1]/div[1]/div[3]/cr-table[1]/table[1]/tbody[1]/tr[1]/td[1]/app-actions[1]/cr-table-actions[1]/cr-dropdown-menu[1]/cr-popover-container[1]/trigger[1]/cr-button[1]/button[1]/cr-icon[1]/fa-icon[1]/*[name()='svg'][1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>cr-shadow-dom-portal:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; app-subject-table:nth-of-type(1) &gt; cr-data-table:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(3) &gt; cr-table:nth-of-type(1) &gt; table:nth-of-type(1) &gt; tbody:nth-of-type(1) &gt; tr:nth-of-type(1) &gt; td:nth-of-type(1) &gt; app-actions:nth-of-type(1) &gt; cr-table-actions:nth-of-type(1) &gt; cr-dropdown-menu:nth-of-type(1) &gt; cr-popover-container:nth-of-type(1) &gt; trigger:nth-of-type(1) &gt; cr-button:nth-of-type(1) &gt; button:nth-of-type(1) &gt; cr-icon:nth-of-type(1) &gt; fa-icon:nth-of-type(1) &gt; svg:nth-of-type(1)</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.inline-block &gt; cr-button &gt; .button &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_dashboard/crShadowDom_object48</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>3edbd66a-73fd-4424-9fc8-ac35e35e111b</webElementGuid>
    </webElementProperties>
</WebElementEntity>