<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7a38ffbb-4e1d-417a-9c00-4bc118bba20c</elementGuidId>
    <imagePath></imagePath>
    <name>input_scanner</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//cr-shadow-dom-portal/div[1]/cr-modals-container[1]/cr-modal-opener[1]/cr-modal[1]/dialog[1]/div[1]/view-device-modal[1]/form[1]/cr-modal-body[1]/div[1]/span[1]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>.items-center &gt; [type="checkbox"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@name,'Scanner') and equals(@type,'checkbox')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"view-device\"] [id=\"\\31 00646\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>Scanner</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>checkbox</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_dashboard/crShadowDom_object12</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>