<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1be10dfd-b32a-414e-ace5-ab3eddc1f369</elementGuidId>
    <imagePath></imagePath>
    <name>textarea_object2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//cr-shadow-dom-portal/div[1]/cr-modals-container[1]/cr-modal-opener[1]/cr-modal[1]/dialog[1]/div[1]/add-questionnaire-modal[1]/form[1]/cr-modal-body[1]/div[1]/imgsh-form[1]/div[1]/div[1]/form[1]/imgsh-form-node-renderer[1]/imgsh-form-screen[1]/div[1]/imgsh-form-node-renderer[1]/imgsh-form-field[15]/imgsh-form-field-wrapper[1]/div[1]/div[1]/div[1]/imgsh-form-field-renderer[1]/div[1]/imgsh-form-text-area-field[1]/div[1]/imgsh-form-expandable-input-wrapper[1]/div[1]/div[1]/cr-input[1]/div[1]/textarea[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="\31 091243\.0"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[id=\"\\31 091243\\.0\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Tracking Environment/Page_studies_dashboard/crShadowDom_object12</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element_is_shadow_root</name>
        <type>Main</type>
        <value>true</value>
        <webElementGuid>5cb02c54-f36b-4548-b490-1c4fd7de3bdf</webElementGuid>
    </webElementProperties>
</WebElementEntity>