<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0f072b4e-32c7-429b-b58f-a045ee941ab0</elementGuidId>
    <imagePath></imagePath>
    <name>html_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//html</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>html</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>html</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>