<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9f913d3d-e1dc-47ae-b084-2d162ce11bce</elementGuidId>
    <imagePath></imagePath>
    <name>header_iframeSameDomain</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/main[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/h1[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiCollapse-root\ MuiCollapse-vertical\ MuiCollapse-entered\ css-1cbf1l2"] .font-bold</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>h1 &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>