<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9fc6dff7-9205-484a-915f-4579a5d90952</elementGuidId>
    <imagePath></imagePath>
    <name>button_databaseActions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[2]/div[1]/div[1]/div[3]/main[1]/div[2]/nav[2]/div[1]/div[2]/div[2]/div[1]/ul[1]/li[2]/div[1]/div[2]/ul[1]/li[1]/div[1]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="${button_databaseActions_id}"] &gt; [class="awsui_icon-container_gwq0h_piid9_264\ awsui_expand-button_gwq0h_piid9_246"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>div &gt;&gt; internal:has-text=/^${button_databaseActions_internalHasText}$/ &gt;&gt; internal:label=\"${button_databaseActions_internalLabel}\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>842fadf0-f475-4784-ad16-f58882c9c597</webElementGuid>
    </webElementProperties>
</WebElementEntity>