<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>3e26fee3-b894-4297-9b9c-70e68fc96bed</elementGuidId>
    <imagePath></imagePath>
    <name>input_submit2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[10]/div[2]/input[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="submitButtonDialogBox\ button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:label=\"Dock Layout Reset\"i &gt;&gt; internal:text=\"Submit\"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>c234667e-46e0-49a7-9fd1-073bddb14cc8</webElementGuid>
    </webElementProperties>
</WebElementEntity>