<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5ff46cdc-d2bd-4d26-9822-180862d3f159</elementGuidId>
    <imagePath></imagePath>
    <name>item_jobTitleAutomationSpecialist</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//div/div[3]/ul[1]/li[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'jobTitle.Automation Specialist')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>jobTitle.Automation Specialist</value>
        <webElementGuid>b6e89a31-3aa9-45a9-9425-519a7550ac18</webElementGuid>
    </webElementProperties>
</WebElementEntity>