<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e6605659-3b9d-4cb1-973c-30e6be53b0ac</elementGuidId>
    <imagePath></imagePath>
    <name>item_saveChanged</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/strong[1]/div[3]/table[1]/tbody[1]/tr[4]/td[11]/ul[1]/li[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>tr:nth-of-type(4) [class="save_changed\ save_edit_record\ active_on"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>.save_changed &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>