<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>27eab789-407d-4656-a941-18c50665cb7c</elementGuidId>
    <imagePath></imagePath>
    <name>link_recentlyViewed</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/div[2]/div[1]/div[1]/span[1]/header[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/span[1]/span[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="link-174382"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'link-174382') and equals(@id,'link-174382') and equals(@href,'{{url}}?searchObjectId=174382&amp;searchContainerId=10238&amp;searchContentType=issue&amp;searchSessionId=9816725a-6810-474a-85a0-f77d019d0ff9') and equals(@text,'KIP-4582 [TrueTest POC] R&amp;L Carriers
            Katalon Intelligent Platform
            •
            Recently viewed')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"link-174382\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>link-174382</value>
        <webElementGuid>2acf07fb-47af-4ffd-8e74-1d49995c2e55</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}?searchObjectId=174382&amp;searchContainerId=10238&amp;searchContentType=issue&amp;searchSessionId=9816725a-6810-474a-85a0-f77d019d0ff9</value>
        <webElementGuid>2acf07fb-47af-4ffd-8e74-1d49995c2e55</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>link-174382</value>
        <webElementGuid>2acf07fb-47af-4ffd-8e74-1d49995c2e55</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>KIP-4582 [TrueTest POC] R&amp;L Carriers
        Katalon Intelligent Platform
        •
        Recently viewed</value>
        <webElementGuid>2acf07fb-47af-4ffd-8e74-1d49995c2e55</webElementGuid>
    </webElementProperties>
</WebElementEntity>