<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fa4bffca-1839-4fe5-9ddf-f34e5896caa9</elementGuidId>
    <imagePath></imagePath>
    <name>div_createTestRunHeader3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[class="MuiInputBase-root\ MuiOutlinedInput-root\ MuiInputBase-colorPrimary\ MuiInputBase-fullWidth\ Mui-focused\ MuiInputBase-formControl\ MuiInputBase-sizeSmall\ MuiInputBase-adornedEnd\ MuiAutocomplete-inputRoot\ css-n2b5kz"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"create-test-run-header-sprint-selector\"] div &gt;&gt; nth=2</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>