<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b6f453bb-99b4-45b7-a448-46752ddb0a8a</elementGuidId>
    <imagePath></imagePath>
    <name>code_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/div[2]/div[3]/div[2]/main[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/div[5]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/form[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[2]/li[2]/p[1]/code[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>li:nth-of-type(2) [class="_ca0qyh40\ _u5f3m5ip\ _n3tdyh40\ _19bvm5ip\ _2rko1sit\ _11c81u0j\ _1reo1wug\ _18m91wug\ _1dqoglyw\ _1e0c1nu9\ _bfhktkvp\ _16d9qvcn\ _syaz1fxt\ _vwz41kw7\ _1i4q1hna\ _o5721jtm"]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>code &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>