<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b74ba454-2aab-4003-9a63-b08ad139b94d</elementGuidId>
    <imagePath></imagePath>
    <name>link_issueResolvedView</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/div[1]/div[2]/div[3]/div[2]/main[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/span[1]/span[1]/div[3]/div[1]/span[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/p[3]/span[2]/span[1]/span[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>span:nth-of-type(2) [role="button"] &gt; [role="button"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'inline-card-resolved-view') and equals(@href,'{{url}}') and equals(@text,'R&amp;L POC')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"issue-comment-base\\.ui\\.comment\\.ak-comment\\.225710-content\"] [data-testid=\"inline-card-resolved-view\"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>inline-card-resolved-view</value>
        <webElementGuid>2acf07fb-47af-4ffd-8e74-1d49995c2e55</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>2acf07fb-47af-4ffd-8e74-1d49995c2e55</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>R&amp;L POC</value>
        <webElementGuid>2acf07fb-47af-4ffd-8e74-1d49995c2e55</webElementGuid>
    </webElementProperties>
</WebElementEntity>