<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>783688c1-c3a9-4da3-858a-b7f225b6d6e8</elementGuidId>
    <imagePath></imagePath>
    <name>link_recordingSession</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[3]/div[2]/main[1]/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[1]/span[1]/span[1]/div[3]/div[5]/span[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/ul[1]/li[1]/p[1]/span[1]/span[1]/span[1]/span[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>body:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(3) &gt; div:nth-of-type(2) &gt; main:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(3) &gt; div:nth-of-type(2) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; span:nth-of-type(1) &gt; span:nth-of-type(1) &gt; div:nth-of-type(3) &gt; div:nth-of-type(5) &gt; span:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(1) &gt; div:nth-of-type(2) &gt; div:nth-of-type(1) &gt; ul:nth-of-type(1) &gt; li:nth-of-type(1) &gt; p:nth-of-type(1) &gt; span:nth-of-type(1) &gt; span:nth-of-type(1) &gt; span:nth-of-type(1) &gt; span:nth-of-type(1) &gt; a:nth-of-type(1)</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'inline-card-resolved-view') and equals(@href,'{{url}}') and equals(@text,'R&amp;L Carriers - Katalon TrueTest POC - Working Session - {{date_time}} {{date_time}} PDT - Recording')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid=\"issue-comment-base\\.ui\\.comment\\.ak-comment\\.224061-content\"] [data-testid=\"inline-card-resolved-view\"] &gt;&gt; nth=0</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>inline-card-resolved-view</value>
        <webElementGuid>8305829a-2b2f-4c8e-bf8f-a92b1c012308</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>8305829a-2b2f-4c8e-bf8f-a92b1c012308</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>R&amp;L Carriers - Katalon TrueTest POC - Working Session - {{date_time}} {{date_time}} PDT - Recording</value>
        <webElementGuid>8305829a-2b2f-4c8e-bf8f-a92b1c012308</webElementGuid>
    </webElementProperties>
</WebElementEntity>