<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b5fcf700-6c34-4af4-9627-8c58f71d74ce</elementGuidId>
    <imagePath></imagePath>
    <name>input_position3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[3]/div[2]/div[2]/div[10]/input[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[id="btnPos3"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'btnPos3') and equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#bottomLeftDiv &gt;&gt; internal:text=\"3\"s</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>btnPos3</value>
        <webElementGuid>c234667e-46e0-49a7-9fd1-073bddb14cc8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>c234667e-46e0-49a7-9fd1-073bddb14cc8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>ref_element</name>
        <type>Main</type>
        <value>Object Repository/AI-Generated/Page_move_shipment/iframe_object4</value>
        <webElementGuid>c234667e-46e0-49a7-9fd1-073bddb14cc8</webElementGuid>
    </webElementProperties>
</WebElementEntity>